title: querido
description: A CLI toolkit for common data analysis tasks against SQLite, DuckDB, Snowflake, and Parquet files.
url: https://curtisalexander.github.io
baseurl: /querido

exclude:
  - Gemfile
  - Gemfile.lock
